## QFGB8960 Advanced C++ for Finance

In [2]:
import qflib as qf
import numpy as np
import os

print("qflib version: {0}".format(qf.version()))
print("pid: {0}".format(os.getpid()))

qflib version: 0.1.0-debug
pid: 12344


Question 1 Solutions

1. Sizes of Data
   (a) Boolean size: 8 bits
   (b) Double size: 64 bits

2. Integer Arithmetic
   Output: -1 1

3. Integers and Logicals
   Output: 16

4. Pre/Post Increment
   Output: 1 0

5. Short-Circuiting Logical Operations
   Output: 0 0

6. Operator Overloading
   (b) % - Can be overloaded
   (d) == - Can be overloaded

7. Reference Modification
   Output: 10

8. Constructors and Destructors
   1
   3
   4
   2

9. Lambda Function
   Output: 0 0

10. Template Functions
   1 0
   2 1
   1.2 0


In [3]:
p = [0, 2]
q = [1, 0, 3]

result = qf.polyProd(p, q)
print(result)  # Expected output: [0, 2, 0, 6]

[0. 2. 0. 6.]


In [4]:
pascal = [np.array([1.]), np.array([1., 1.])]

# Generate six more rows using qf.polyProd
for i in range(6):
    new_row = qf.polyProd(pascal[-1], [1., 1.])
    pascal.append(new_row)

# Print Pascal's Triangle
for row in pascal:
    print(row)

[1.]
[1. 1.]
[1. 2. 1.]
[1. 3. 3. 1.]
[1. 4. 6. 4. 1.]
[ 1.  5. 10. 10.  5.  1.]
[ 1.  6. 15. 20. 15.  6.  1.]
[ 1.  7. 21. 35. 35. 21.  7.  1.]
